In [41]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt

CATEGORIES = ["Dog", "Cat"]
SIZE = 52
data = []


direc = "C:/users/bhavy/Documents/RANDOM_PROJECTS/DeepLearning/data/PetImages"

def preprocess(img):
    img = cv2.resize(img, (SIZE, SIZE))
    return img

for cat in CATEGORIES:
    directory = os.path.join(direc, cat)
    
    for i in os.listdir(directory):
        try:
            img = cv2.imread(os.path.join(directory, i), 0)
            data.append([preprocess(img), CATEGORIES.index(cat)])
        except Exception as e:
            pass

In [44]:
import random
random.shuffle(data)

In [55]:
X = []
y = []

for features,labels in data:
    X.append(features)
    y.append(labels)

X = np.array(X).reshape(-1, SIZE, SIZE, 1)
y = np.array(y)

In [56]:
import pickle

pickle_out = open("X.pickle", "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle", "wb")
pickle.dump(y, pickle_out)
pickle_out.close()

[[[0.74509804]
  [0.76862745]
  [0.79215686]
  ...
  [0.64313725]
  [0.64705882]
  [0.56862745]]

 [[0.76470588]
  [0.78823529]
  [0.8       ]
  ...
  [0.67843137]
  [0.62352941]
  [0.61176471]]

 [[0.77254902]
  [0.79607843]
  [0.80784314]
  ...
  [0.65098039]
  [0.63529412]
  [0.62352941]]

 ...

 [[0.61176471]
  [0.63529412]
  [0.65882353]
  ...
  [0.41176471]
  [0.48235294]
  [0.27843137]]

 [[0.59607843]
  [0.61568627]
  [0.64313725]
  ...
  [0.47843137]
  [0.46666667]
  [0.4745098 ]]

 [[0.57254902]
  [0.59607843]
  [0.61960784]
  ...
  [0.48627451]
  [0.45882353]
  [0.45098039]]]
